In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
from random import sample
from collections import Counter
import string
from sklearn.dummy import DummyClassifier
from numpy.random import random_integers
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
from sklearn.naive_bayes import BernoulliNB
from sklearn import tree
from sklearn.svm import LinearSVC

In [2]:
def readTxt(fileName):
    fullFileName = r'C:\Users\Owner\McGill\4thYear\COMP551\Assignments\Assignment3\Datasets' + fileName
    df = pd.read_csv(fullFileName, encoding='utf-8', header = None,
                 sep='\t')
    
    return df

In [3]:
def readCsv(fileName):
    fullFileName = r'C:\Users\Owner\McGill\4thYear\COMP551\Assignments\Assignment3' + fileName
    df = pd.read_csv(fullFileName, encoding='utf-8', header = None,
                 sep=',')
    
    return df

In [4]:
def toCsvDf(fileName, df):
    fullFileName = r'C:\Users\Owner\McGill\4thYear\COMP551\Assignments\Assignment3\Datasets' + fileName
    df.to_csv(fullFileName, header = False, sep='\t', index = False)

In [5]:
def toCsvNp(fileName, npArray):
    fullFileName = r'C:\Users\Owner\McGill\4thYear\COMP551\Assignments\Assignment3\Datasets' + fileName
    np.savetxt(fullFileName, npArray, delimiter=',')

In [6]:
def createDictionary(trainingSet):
    allWords = list()
    cnt = Counter()
    
    if trainingSet=='IMDB':
        trainingDF = readTxt('\IMDB-train.txt')
    elif trainingSet=='yelp':
        trainingDF = readTxt('\yelp-train.txt')
        
    translator = str.maketrans('','', string.punctuation)
    
    for i in range(0, len(trainingDF)):
        allWords.extend(trainingDF.iloc[i,0].translate(translator).lower().split(" "))
    
    for word in allWords:
        cnt[word] +=1
    
    dictionaryWords = list(zip(*cnt.most_common(10000)))[0]
    
    dictionary = {}
    for index, key in enumerate(dictionaryWords):
        dictionary[key] = index
#     print(dictionary)
    newArray = np.asarray(cnt.most_common(10000))
    withIndexVocabArray = np.insert(newArray, 1, range(0,10000),1)
    
#     if trainingSet=='IMDB':
#         toCsvDf('\IMDB-vocab.txt', pd.DataFrame(withIndexVocabArray))
#     elif trainingSet=='yelp':
#         toCsvDf('\yelp-vocab.txt', pd.DataFrame(withIndexVocabArray))
        
    return dictionary

In [74]:
def convertWordsToVector(trainingRow, dictionary, BOWType):
    translator = str.maketrans('','', string.punctuation)
    returnRow = trainingRow.translate(translator).lower().split(" ")
    vector = np.zeros(10000, dtype = np.int8)
    
    for word in returnRow:
        if word in dictionary:
            if BOWType == 'BagOfWords':
                vector[dictionary[word]] = np.int8(1)
            elif BOWType == 'Frequency':
                vector[dictionary[word]] += 1
    
    if BOWType == 'Frequency':
#         To accomodate for the fact that one of the rows has one word, d-gust-ing, and the lenght of the vector is zero.
#         Hence, the vector returns [Nan Nan Nan ... Nan Nan].  Now it returns [0 0 0 ... 0 0 0]
        vectorLength =  np.sum(vector)
        if vectorLength>0:
            vector = np.divide(vector, vectorLength)
            
    return vector

In [77]:
def createBagOfWordsMatrix(df, dictionary, BOWType):
    translator = str.maketrans('','', string.punctuation)
    
    if BOWType == 'BagOfWords':
        distancesArray = np.zeros((len(df), len(dictionary)), dtype = np.int8)
    elif BOWType == 'Frequency':
        distancesArray = np.zeros((len(df), len(dictionary)))
        
    for i in range(0, len(df)):
        vector = convertWordsToVector(df.iloc[i,0], dictionary, BOWType)
        distancesArray[i] = vector
#         print(np.sum(distancesArray[i]))
    return distancesArray
# trainingDF = 
npArray = createBagOfWordsMatrix(readTxt('\yelp-train.txt'), createDictionary('yelp'), 'Frequency')
print(npArray)
# dfArray = pd.DataFrame(npArray)
# dfArray.to_csv(r'C:\Users\Owner\McGill\4thYear\COMP551\Assignments\Assignment3\Datasets\TESTING2.csv', header = False, sep=',', index = False)

[[ 0.05434783  0.02173913  0.00543478 ...,  0.          0.          0.        ]
 [ 0.03488372  0.03488372  0.0872093  ...,  0.          0.          0.        ]
 [ 0.05555556  0.03703704  0.04938272 ...,  0.          0.          0.        ]
 ..., 
 [ 0.03333333  0.075       0.04166667 ...,  0.          0.          0.        ]
 [ 0.08029197  0.03832117  0.05291971 ...,  0.          0.          0.        ]
 [ 0.02777778  0.05555556  0.         ...,  0.          0.          0.        ]]


In [ ]:
def createFrequencyBagOfWordsMatrix(df, dictionary):
    translator = str.maketrans('','', string.punctuation)
    
    distancesArray = np.zeros((len(df), len(dictionary)), dtype=np.int8)
        
    for i in range(0, len(df)):
        vector = convertWordsToVector(df.iloc[i,0], dictionary)
        distancesArray[i] = vector

    return distancesArray
createFrequencyBagOfWordsMatrix(readTxt('\yelp-train.txt'), createDictionary())

In [10]:
def testScores(predicted, actual):
    print('F1 Score:', f1_score(actual, predicted, average='macro'))
    print('Confusion Matrix:\n', confusion_matrix(actual, predicted))

In [11]:
def randomClassifier(dataset):
    print(dataset, 'Random Classifier')
    if dataset == 'yelp':
        dictionary = createDictionary('yelp')
        trainingDF = readTxt('\yelp-train.txt')
        validDF = readTxt('\yelp-valid.txt')
        testDF = readTxt('\yelp-test.txt')
    elif dataset == 'IMDB':
        dictionary = createDictionary('IMDB')
        trainingDF = readTxt('\IMDB-train.txt')
        validDF = readTxt('\IMDB-valid.txt')
        testDF = readTxt('\IMDB-test.txt')
    
    randomClassifier = DummyClassifier(strategy='uniform')
    randomClassifier.fit(createBagOfWordsMatrix(trainingDF, dictionary), trainingDF[1])
    
    print('Training F1-Measure')
    predictionsArray = randomClassifier.predict(createBagOfWordsMatrix(trainingDF, dictionary))
    testScores(predictionsArray, trainingDF[1])
    
    print('Validation F1-Measure')
    predictionsArray = randomClassifier.predict(createBagOfWordsMatrix(validDF, dictionary))
    testScores(predictionsArray, validDF[1])
    
    print('Test F1-Measure')
    predictionsArray = randomClassifier.predict(createBagOfWordsMatrix(testDF, dictionary))
    testScores(predictionsArray, testDF[1])
    
randomClassifier('yelp')

yelp Random Classifier
Training F1-Measure
F1 Score: 0.184123905128
Confusion Matrix:
 [[107 106  96 119  94]
 [124 129 115 137 136]
 [202 203 199 199 194]
 [503 478 484 497 506]
 [473 462 483 464 490]]
Validation F1-Measure
F1 Score: 0.176673463167
Confusion Matrix:
 [[14 15 23 18 14]
 [24 16 20 12 24]
 [25 35 37 34 33]
 [62 68 82 74 70]
 [58 48 70 71 53]]
Test F1-Measure
F1 Score: 0.18894982874
Confusion Matrix:
 [[ 27  29  25  33  29]
 [ 37  40  38  36  39]
 [ 63  54  60  65  58]
 [126 164 135 145 132]
 [122 127 133 136 147]]


In [12]:
def majorityClassifier(dataset):
    print(dataset, 'Majority Classifier')
    if dataset == 'yelp':
        dictionary = createDictionary('yelp')
        trainingDF = readTxt('\yelp-train.txt')
        validDF = readTxt('\yelp-valid.txt')
        testDF = readTxt('\yelp-test.txt')
    elif dataset == 'IMDB':
        dictionary = createDictionary('IMDB')
        trainingDF = readTxt('\IMDB-train.txt')
        validDF = readTxt('\IMDB-valid.txt')
        testDF = readTxt('\IMDB-test.txt')
    
    majorityClassifier = DummyClassifier(strategy='most_frequent')
    majorityClassifier.fit(createBagOfWordsMatrix(trainingDF, dictionary), trainingDF[1])
    
    print('Training F1-Measure')
    predictionsArray = majorityClassifier.predict(createBagOfWordsMatrix(trainingDF, dictionary))
    testScores(predictionsArray, trainingDF[1])
    
    print('Validation F1-Measure')
    predictionsArray = majorityClassifier.predict(createBagOfWordsMatrix(validDF, dictionary))
    testScores(predictionsArray, validDF[1])
    
    print('Test F1-Measure')
    predictionsArray = majorityClassifier.predict(createBagOfWordsMatrix(testDF, dictionary))
    testScores(predictionsArray, testDF[1])
    
# baselineClassifier('IMDB')
majorityClassifier('yelp')

yelp Majority Classifier
Training F1-Measure


C:\Users\Owner\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


F1 Score: 0.104267004647
Confusion Matrix:
 [[   0    0    0  522    0]
 [   0    0    0  641    0]
 [   0    0    0  997    0]
 [   0    0    0 2468    0]
 [   0    0    0 2372    0]]
Validation F1-Measure
F1 Score: 0.105014749263
Confusion Matrix:
 [[  0   0   0  84   0]
 [  0   0   0  96   0]
 [  0   0   0 164   0]
 [  0   0   0 356   0]
 [  0   0   0 300   0]]
Test F1-Measure
F1 Score: 0.103923019985
Confusion Matrix:
 [[  0   0   0 143   0]
 [  0   0   0 190   0]
 [  0   0   0 300   0]
 [  0   0   0 702   0]
 [  0   0   0 665   0]]


In [13]:
def bernoulliNB(dataset):
    print(dataset)
    if dataset == 'yelp':
        dictionary = createDictionary('yelp')
        trainingDF = readTxt('\yelp-train.txt')
        validDF = readTxt('\yelp-valid.txt')
        testDF = readTxt('\yelp-test.txt')
    elif dataset == 'IMDB':
        dictionary = createDictionary('IMDB')
        trainingDF = readTxt('\IMDB-train.txt')
        validDF = readTxt('\IMDB-valid.txt')
        testDF = readTxt('\IMDB-test.txt')
        
    clf = BernoulliNB()
    clf.fit(createBagOfWordsMatrix(trainingDF, dictionary), trainingDF[1])
    
    print('Training F1-Measure')
    predictionsArray = clf.predict(createBagOfWordsMatrix(trainingDF, dictionary))
    testScores(predictionsArray, trainingDF[1])
    
    print('Validation F1-Measure')
    predictionsArray = clf.predict(createBagOfWordsMatrix(validDF, dictionary))
    testScores(predictionsArray, validDF[1])
    
    print('Test F1-Measure')
    predictionsArray = clf.predict(createBagOfWordsMatrix(testDF, dictionary))
    testScores(predictionsArray, testDF[1])
    
bernoulliNB('yelp')

yelp
Training F1-Measure
F1 Score: 0.580313605691
Confusion Matrix:
 [[ 274    5   17   22  204]
 [   9  320   28   85  199]
 [  10   27  474  157  329]
 [  36  144   83 1237  968]
 [  50  121   75  247 1879]]
Validation F1-Measure
F1 Score: 0.326966475705
Confusion Matrix:
 [[ 27  12   5   6  34]
 [  9  17  11  27  32]
 [  4  21  28  55  56]
 [  9  29  27 119 172]
 [ 11  22  14  64 189]]
Test F1-Measure
F1 Score: 0.342970426948
Confusion Matrix:
 [[ 40  24   6  21  52]
 [ 20  47  33  29  61]
 [ 11  34  47  94 114]
 [  9  58  63 250 322]
 [ 10  38  24 153 440]]


In [14]:
def decisionTree(dataset):
    print(dataset)
    if dataset == 'yelp':
        dictionary = createDictionary('yelp')
        trainingDF = readTxt('\yelp-train.txt')
        validDF = readTxt('\yelp-valid.txt')
        testDF = readTxt('\yelp-test.txt')
    elif dataset == 'IMDB':
        dictionary = createDictionary('IMDB')
        trainingDF = readTxt('\IMDB-train.txt')
        validDF = readTxt('\IMDB-valid.txt')
        testDF = readTxt('\IMDB-test.txt')
        
    clf = tree.DecisionTreeClassifier()
    clf.fit(createBagOfWordsMatrix(trainingDF, dictionary), trainingDF[1])
    
    print('Training F1-Measure')
    predictionsArray = clf.predict(createBagOfWordsMatrix(trainingDF, dictionary))
    testScores(predictionsArray, trainingDF[1])
    
    print('Validation F1-Measure')
    predictionsArray = clf.predict(createBagOfWordsMatrix(validDF, dictionary))
    testScores(predictionsArray, validDF[1])
    
    print('Test F1-Measure')
    predictionsArray = clf.predict(createBagOfWordsMatrix(testDF, dictionary))
    testScores(predictionsArray, testDF[1])
    
decisionTree('yelp')

yelp
Training F1-Measure
F1 Score: 1.0
Confusion Matrix:
 [[ 522    0    0    0    0]
 [   0  641    0    0    0]
 [   0    0  997    0    0]
 [   0    0    0 2468    0]
 [   0    0    0    0 2372]]
Validation F1-Measure
F1 Score: 0.279822135371
Confusion Matrix:
 [[ 19  13  14  14  24]
 [ 13  11  17  24  31]
 [  8  21  40  58  37]
 [ 19  31  57 137 112]
 [ 15  17  31 110 127]]
Test F1-Measure
F1 Score: 0.276493554759
Confusion Matrix:
 [[ 24  24  27  31  37]
 [ 22  28  42  57  41]
 [ 11  33  59 133  64]
 [ 37  44  91 278 252]
 [ 25  35  60 237 308]]


In [15]:
def linearSVC(dataset):
    print(dataset)
    if dataset == 'yelp':
        dictionary = createDictionary('yelp')
        trainingDF = readTxt('\yelp-train.txt')
        validDF = readTxt('\yelp-valid.txt')
        testDF = readTxt('\yelp-test.txt')
    elif dataset == 'IMDB':
        dictionary = createDictionary('IMDB')
        trainingDF = readTxt('\IMDB-train.txt')
        validDF = readTxt('\IMDB-valid.txt')
        testDF = readTxt('\IMDB-test.txt')
        
    clf = LinearSVC()
    clf.fit(createBagOfWordsMatrix(trainingDF, dictionary), trainingDF[1])
    
    print('Training F1-Measure')
    predictionsArray = clf.predict(createBagOfWordsMatrix(trainingDF, dictionary))
    testScores(predictionsArray, trainingDF[1])
    
    print('Validation F1-Measure')
    predictionsArray = clf.predict(createBagOfWordsMatrix(validDF, dictionary))
    testScores(predictionsArray, validDF[1])
    
    print('Test F1-Measure')
    predictionsArray = clf.predict(createBagOfWordsMatrix(testDF, dictionary))
    testScores(predictionsArray, testDF[1])
    
linearSVC('yelp')

yelp
Training F1-Measure
F1 Score: 0.997870801179
Confusion Matrix:
 [[ 520    0    0    0    2]
 [   0  640    0    0    1]
 [   0    0  996    1    0]
 [   0    0    0 2454   14]
 [   0    0    0    2 2370]]
Validation F1-Measure
F1 Score: 0.413428426203
Confusion Matrix:
 [[ 36  23   8   9   8]
 [ 14  25  15  28  14]
 [  7  23  50  65  19]
 [ 10  11  32 170 133]
 [  4   9  18 102 167]]
Test F1-Measure
F1 Score: 0.401651918294
Confusion Matrix:
 [[ 56  33  15  19  20]
 [ 33  58  41  36  22]
 [ 12  42  77 118  51]
 [ 12  31  84 340 235]
 [ 15  12  40 237 361]]
